backend:
  name: github
  repo: paymentshield/api-docs

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - name: sections
    label: Sections
    folder: source/includes/
    create: true
    preview_path: /
    editor:
      preview: true
    summary: "{{filename}}"
    fields:
      - {label: Body, name: body, widget: markdown}
  - name: 'pages'
    label: 'Pages'
    create: false
    preview_path: /
    editor:
      preview: true
    files:
      - label: 'Main Page'
        name: 'index'
        file: 'index.html.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Sections', name: 'includes', widget: 'list' }
          - { label: 'TOC Links', name: 'toc_footers', widget: 'list' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

