backend:
  name: github
  repo: paymentshield/api-docs

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - name: sections
    label: Sections
    folder: source/includes/
    create: true
    preview_path: /
    summary: "{{filename}}"
    fields:
      - {label: Body, name: body, widget: markdown}
